
<?php
/**
 * @file
 * This is the main module file.
 */


//include_once 'owasp_xss.inc';
//include_once 'owasp_sqli.inc';
//include_once 'owasp_csrf.inc';
//include_once 'owasp_no_csrf.inc';

 /**
 * Implements hook_help().
 */
function drupal_owasp_top10_help($path, $arg) {

  if ($path == 'admin/help#owasp') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The owasp module implements the OWASP TOP 10 vulnerabilities.') . '</p>';
    return $output;
  }
}



/**
* Implementation of hook_menu().
*/
function drupal_owasp_top10_menu() {

$items['owasp'] = array(
	'title' => 'TOP 10 OWASP',       
	'page callback' => array('owasp_page_callback'),
	'access callback' => TRUE,
	'type' => MENU_NORMAL_ITEM
         
        );
 
$items['owasp/Reflected XSS'] = array(
	'title' => 'Reflected XSS',        
	'access callback' => TRUE,
	'access arguments' => array('access content'),	
	'page callback' => 'drupal_get_form',
	'page arguments'=>array('owasp_xss_form'),
	'file' => 'owasp_xss.inc',
	'file path' => drupal_get_path('module', 'drupal_owasp_top10') . '/includes',
	'type' => MENU_NORMAL_ITEM
        );

$items['owasp/SQL Injection'] = array(
	'title' => 'SQL Injection',        
	'access callback' => TRUE,	
    'access arguments' => array('access content'),
	'page callback' => 'drupal_get_form',
    'page arguments'=>array('owasp_sqli_form'),
	'file' => 'owasp_sqli.inc', 
	'file path' => drupal_get_path('module', 'drupal_owasp_top10') . '/includes',
	'type' => MENU_NORMAL_ITEM
        );

$items['owasp/CSRF/csrf_using_anonymous_form'] = array(
	'title' => 'CSRF (anonymous form)',        
	'access callback' => TRUE,
    'access arguments' => array('access content'),
	'page callback' => 'drupal_get_form',
    'page arguments'=>array('owasp_csrf_form'),
	'file' => 'owasp_csrf.inc',
	'file path' => drupal_get_path('module', 'drupal_owasp_top10') . '/includes',
	'type' => MENU_NORMAL_ITEM
        );

$items['owasp/CSRF/csrf_using_authenticated_form'] = array(
     'title' => 'CSRF (authenticated form)',
      'access callback' => TRUE ,
      'access arguments' => array('access content'),
	  'page callback' => 'drupal_get_form',
      'page arguments'=>array('owasp_no_csrf_form'),
	  'file' => 'owasp_no_csrf.inc',
	  'file path' => drupal_get_path('module', 'drupal_owasp_top10') . '/includes',
      'type' => MENU_NORMAL_ITEM
        );


  return $items;
}

function owasp_page_callback(){

$result = "Ce projet consiste à implémenter l'ensemble du TOP 10 OWASP sous Drupal7. Le but étant de fournir les recommendations et les bonnes pratiques à suivre en terme de développement des sites internet avec Drupal.";

    return $result;

}

 
 


 
 

